/* tslint:disable */
/* eslint-disable */
/**
 * Stable - Auth Service
 * An authentication service API for Stable
 *
 * The version of the OpenAPI document: 0.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConfirmForgotPasswordRequestDto
 */
export interface ConfirmForgotPasswordRequestDto {
    /**
     * The email of the user
     * @type {string}
     * @memberof ConfirmForgotPasswordRequestDto
     */
    email: string;
    /**
     * The verification code sent to the email
     * @type {string}
     * @memberof ConfirmForgotPasswordRequestDto
     */
    verificationCode: string;
    /**
     * The password of the user
     * @type {string}
     * @memberof ConfirmForgotPasswordRequestDto
     */
    newPassword: string;
}

/**
 * Check if a given object implements the ConfirmForgotPasswordRequestDto interface.
 */
export function instanceOfConfirmForgotPasswordRequestDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "verificationCode" in value;
    isInstance = isInstance && "newPassword" in value;

    return isInstance;
}

export function ConfirmForgotPasswordRequestDtoFromJSON(json: any): ConfirmForgotPasswordRequestDto {
    return ConfirmForgotPasswordRequestDtoFromJSONTyped(json, false);
}

export function ConfirmForgotPasswordRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConfirmForgotPasswordRequestDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'verificationCode': json['verificationCode'],
        'newPassword': json['newPassword'],
    };
}

export function ConfirmForgotPasswordRequestDtoToJSON(value?: ConfirmForgotPasswordRequestDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'verificationCode': value.verificationCode,
        'newPassword': value.newPassword,
    };
}

