/* tslint:disable */
/* eslint-disable */
/**
 * Stable - Auth Service
 * An authentication service API for Stable
 *
 * The version of the OpenAPI document: 0.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ForgotPasswordRequestDto
 */
export interface ForgotPasswordRequestDto {
    /**
     * The email of the user
     * @type {string}
     * @memberof ForgotPasswordRequestDto
     */
    email: string;
}

/**
 * Check if a given object implements the ForgotPasswordRequestDto interface.
 */
export function instanceOfForgotPasswordRequestDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;

    return isInstance;
}

export function ForgotPasswordRequestDtoFromJSON(json: any): ForgotPasswordRequestDto {
    return ForgotPasswordRequestDtoFromJSONTyped(json, false);
}

export function ForgotPasswordRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ForgotPasswordRequestDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
    };
}

export function ForgotPasswordRequestDtoToJSON(value?: ForgotPasswordRequestDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
    };
}

