/* tslint:disable */
/* eslint-disable */
/**
 * Stable - Auth Service
 * An authentication service API for Stable
 *
 * The version of the OpenAPI document: 0.0.3
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface LoginUserRequestDto
 */
export interface LoginUserRequestDto {
    /**
     * The email of the user
     * @type {string}
     * @memberof LoginUserRequestDto
     */
    email: string;
    /**
     * The password of the user (minimum 8 characters)
     * @type {string}
     * @memberof LoginUserRequestDto
     */
    password: string;
    /**
     * The new password to set for the user (optional, minimum 8 characters)
     * @type {string}
     * @memberof LoginUserRequestDto
     */
    newPassword?: string;
}

/**
 * Check if a given object implements the LoginUserRequestDto interface.
 */
export function instanceOfLoginUserRequestDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "email" in value;
    isInstance = isInstance && "password" in value;

    return isInstance;
}

export function LoginUserRequestDtoFromJSON(json: any): LoginUserRequestDto {
    return LoginUserRequestDtoFromJSONTyped(json, false);
}

export function LoginUserRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginUserRequestDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': json['email'],
        'password': json['password'],
        'newPassword': !exists(json, 'newPassword') ? undefined : json['newPassword'],
    };
}

export function LoginUserRequestDtoToJSON(value?: LoginUserRequestDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'password': value.password,
        'newPassword': value.newPassword,
    };
}

