/* tslint:disable */
/* eslint-disable */
/**
 * Stable - Auth Service
 * An authentication service API for Stable
 *
 * The version of the OpenAPI document: 0.0.5
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface RefreshTokenRequestDto
 */
export interface RefreshTokenRequestDto {
    /**
     * The refresh token to be used for generating new tokens.
     * @type {string}
     * @memberof RefreshTokenRequestDto
     */
    refreshToken: string;
}

/**
 * Check if a given object implements the RefreshTokenRequestDto interface.
 */
export function instanceOfRefreshTokenRequestDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "refreshToken" in value;

    return isInstance;
}

export function RefreshTokenRequestDtoFromJSON(json: any): RefreshTokenRequestDto {
    return RefreshTokenRequestDtoFromJSONTyped(json, false);
}

export function RefreshTokenRequestDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): RefreshTokenRequestDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'refreshToken': json['refreshToken'],
    };
}

export function RefreshTokenRequestDtoToJSON(value?: RefreshTokenRequestDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'refreshToken': value.refreshToken,
    };
}

